INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-001', 'ARROZ  MASIA 1KG', 'Unidades', '4', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-002', 'ARROZ ANGUIE 1 KG', 'Unidades', '3', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-003', 'ARROZ LA LUCHA 1 KG', 'Unidades', '18', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-004', 'ARROZ GRAN MARQUES 1KG', 'Unidades', '24', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-005', 'ARROZ GRAN MARQUES 2,5 KG', 'Unidades', '7', '1818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-006', 'ARROZ DON PACO 900 GR', 'Unidades', '20', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-007', 'ARROZ DOÑA CATALINA 900 GR', 'Unidades', '10', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-008', 'ARROZ ALVARIGUA 900 GR', 'Unidades', '24', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-009', 'ARROZ SANTONI 900 GR', 'Unidades', '24', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-0010', 'ARROZ PRIMOR TRADICIONAL 900 GR', 'Unidades', '20', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-0011', 'ARROZ PRIMOR SUPERIOR 900 GR', 'Unidades', '20', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-0012', 'ARROZ MARY TRADICIONAL 900 GR', 'Unidades', '24', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-0013', 'ARROZ MARY PREMIUM 900 GR', 'Unidades', '36', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARR-0014', 'ARROZ MARY ESMERALDA 900 GR', 'Unidades', '24', '1363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0015', 'ACEITE VATEL 250 ML ', 'Unidades', '18', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0016', 'ACEITE IDEAL 250 ML ', 'Unidades', '4', '1392.65', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0017', 'ACEITE SAMARA 430 ML', 'Unidades', '6', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0018', 'ACEITE PORTUMESA 485 ML ', 'Unidades', '12', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0019', 'ACEITE VATEL 500 ML ', 'Unidades', '12', '3354.76', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0020', 'ACEITE VATEL 1 LITRO', 'Unidades', '24', '4887.54', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0021', 'ACEITE PUROGOL 900 ML ', 'Unidades', '12', '4208.75', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0022', 'ACEITE ANGUIE 900 ML ', 'Unidades', '24', '243.43', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0023', 'ACEITE ALIMORCA 900 ML ', 'Unidades', '12', '945.99', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0024', 'ACEITE PORTUMESA 850 ML ', 'Unidades', '10', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0025', 'ACEITE LA LUCHA 828 ML ', 'Unidades', '12', '3898.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0026', 'ACEITE COPOSA 850 ML ', 'Unidades', '12', '329.06', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0027', 'ACEITE DE OLIVA 500 ML ', 'Unidades', '5', '5454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ACE-0028', 'ACEITE DE OLIVA 1 LITRO', 'Unidades', '6', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ATU-0029', 'ATUN MARGARITA 140 GR', 'Unidades', '8', '1363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ATU-0030', 'ATUN MARGARITA 170 GR', 'Unidades', '12', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ATU-0031', 'ATUN MARGARITA NATUTAL 170 GR', 'Unidades', '6', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ATU-0032', 'ATUN DON PACO 140 GR', 'Unidades', '10', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ATU-0033', 'ATUN EVEBA EN ACEITE VEGETAL 140 GR', 'Unidades', '5', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ATU-0034', 'ATUN EVEBA EN ACEITE DE OLIVA 140 GR ', 'Unidades', '3', '1454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ATU-0035', 'ATUN EVEBA EN ACEITE 170 GR', 'Unidades', '2', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ATU-0036', 'ATUN EVEBA EN ACEITE DE OLIVA 170 GR', 'Unidades', '2', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ATU-0037', 'ATUN DIMARE EN ACEITE 160 GR', 'Unidades', '6', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ATU-0038', 'ATUN ROBIN HOOD EN ACEITE 160 GR', 'Unidades', '11', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('AZU-0039', 'AZUCAR MONTALBAN 1 KG', 'Unidades', '22', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ADO-0040', 'ADOBO DEL CAMPO 100 GR ', 'Unidades', '8', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ADO-0041', 'ADOBO DEL CAMPO 200 GR ', 'Unidades', '8', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ADO-0042', 'ADOBO LA COMADRE 200 GR ', 'Unidades', '6', '1454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('AZU-0043', 'AZUCAR EL PALACIO 1 KG', 'Unidades', '10', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('AZU-0044', 'AZUCAR SABANA DULCE 1 KG ', 'Unidades', '12', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('AZU-0045', 'AZUCAR BLANCA MICHELENA 1 KG ', 'Unidades', '15', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('AVE-0046', 'AVENA TIGO EN HOJUELAS 200GR', 'Unidades', '5', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('AVE-0047', 'AVENA TIGO EN HOJUELAS 400GR', 'Unidades', '10', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('AVE-0048', 'AVENA LASSI N HOJUELAS 400GR', 'Unidades', '4', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ARV-0049', 'ARVEJA GRANOS RINCON 500 GR', 'Unidades', '20', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('BOC-0050', 'BOCADILLO EL AGUILA 350 GR ', 'Unidades', '40', '545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CAF-0051', 'CAFÉ BRASIL 200 GR ', 'Unidades', '4', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CAF-0052', 'CAFÉ KIWA 200 GR ', 'Unidades', '6', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CAF-0053', 'CAFÉ CONCAFE 400 GR ', 'Unidades', '4', '4181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CAR-0054', 'CARAOTA GRANOS RINCON 500 GR ', 'Unidades', '30', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CHA-0055', 'CHAMPIÑONES TIGO 184 GR ', 'Unidades', '6', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CER-0056', 'CERELAC 900 GR', 'Unidades', '6', '6181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CER-0057', 'CEREAL TIGO ZUKY 100 GR', 'Unidades', '7', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CER-0058', 'CEREAL TIGO FLAKES 100 GR', 'Unidades', '8', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COR-0059', 'CORN FAKES KELLOGGS 230 GR', 'Unidades', '6', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CRE-0060', 'CREMA DE ARROZ PRIMOR 450 GR', 'Unidades', '10', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CRE-0061', 'CREMA DE ARROZ PRIMOR 900 GR', 'Unidades', '1', '1545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CRE-0062', 'CREMA DE ARROZ MARY 450 GR ', 'Unidades', '15', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CHO-0063', 'CHOCOLATE CORONA 200 GR', 'Unidades', '10', '1818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CHO-0064', 'CHOCOLATE CORONA 500  GR', 'Unidades', '7', '3090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CHO-0065', 'CHOCOLATE AROMA 500 GR', 'Unidades', '8', '1818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CHO-0066', 'CHOCO RICO 200 GR', 'Unidades', '8', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CRE-0067', 'CREMA DE LECHE LATTI 200 GR', 'Unidades', '20', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CRE-0068', 'CREMA DE LECHE WYNCO 200 GR', 'Unidades', '6', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COC-0069', 'COCOA CASA REAL 230 GR', 'Unidades', '5', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0070', 'COMPOTA HEINZ BANANA 113 GR', 'Unidades', '8', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0071', 'COMPOTA HEINZ FRUTAS MIXTAS 113 GR', 'Unidades', '10', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0072', 'COMPOTA HEINZ MELOCOTON 113 GR', 'Unidades', '7', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0073', 'COMPOTA HEINZ MANZANA 113 GR', 'Unidades', '11', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0074', 'COMPOTA HEINZ PERA 113 GR', 'Unidades', '12', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0075', 'COMPOTA HEINZ CIRUELAS PASAS 113 GR ', 'Unidades', '6', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0076', 'COMPOTA HEINZ BANANA 186 GR', 'Unidades', '7', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0077', 'COMPOTA HEINZ MANZANA 186 GR', 'Unidades', '15', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0078', 'COMPOTA HEINZ PERA 186 GR', 'Unidades', '15', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0079', 'COMPOTA TIGO FRUTAS MIXTAS 113 GR', 'Unidades', '7', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0080', 'COMPOTA TIGO CIRUELA 113 GR', 'Unidades', '10', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0081', 'COMPOTTA TIGO PERA 113 GR', 'Unidades', '8', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0082', 'COMPOTA TIGO MANZANA 113 GR', 'Unidades', '8', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0083', 'COMPOTA TIGO DURAZNO 113 GR', 'Unidades', '11', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0084', 'COMPOTA NATULAC PERA 186 GR', 'Unidades', '6', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('COM-0085', 'COMPOTA NATULAC MANANA 186 GR', 'Unidades', '3', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CUB-0086', 'CUBITOS TIGO 8 UNI', 'Unidades', '5', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CUB-0087', 'CUBITOS KENT 6 UNI', 'Unidades', '5', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('DIA-0088', 'DIABLITOS UNDER WOOD 54 GR', 'Unidades', '65', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('DIA-0089', 'DIABLITOS UNDER WOOD 115 GR', 'Unidades', '15', '1545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('GAL-0090', 'GALLETA CLUB SOCIAL 6  UNI ', 'Unidades', '10', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('GAL-0091', 'GALLETA MARIA LA PAMPA 150 GR ', 'Unidades', '11', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('GAL-0092', 'GALLETA MARIA CALEDONIA 6 UNI', 'Unidades', '10', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('GEL-0093', 'GELATINA FRUTIÑO 4 UNI SUTIDOS', 'Unidades', '6', '1454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('GEL-0094', 'GELAINA TIGO PARCHITA 25 GR', 'Unidades', '4', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('GEL-0095', 'GELATINA RICOMAX CEREZA 500 GR', 'Unidades', '4', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('GEL-0096', 'GELAINA TIGO LIMON 25 GR', 'Unidades', '4', '545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('GAR-0097', 'GARBANZOS RINCON 500 GR', 'Unidades', '0', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('GUI-0098', 'GUISANTES TIGO 300 GR', 'Unidades', '12', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('HAR-0099', 'HARINA DE MAIZ PAN 1 KG', 'Unidades', '22', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('HAR-00100', 'HARINA DE MAIZ PAN 2 KG', 'Unidades', '6', '1454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('HAR-00101', 'HARINA DE MAIZ MARY 900 GR', 'Unidades', '13', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('HAR-00102', 'HARINA DE MAIZ MARY 2 KG', 'Unidades', '8', '1454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('HAR-00103', 'HARINA DE MAIZ JUANA 900 GR', 'Unidades', '20', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('HAR-00104', 'HARINA DE MAIZ LA LUCHA 1G ', 'Unidades', '20', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('HAR-00105', 'HARINA DE MAIZ OZ 1 KG ', 'Unidades', '24', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('HAR-00106', 'HARINA DE TRIGO LEUDANTE ROBINSON 1 KG ', 'Unidades', '20', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('HAR-00107', 'HARINA DE TRIGO DOÑA MARA 90 GR ', 'Unidades', '1', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('HUE-00108', 'HUEVOS CATON DE 30 UNI', 'Unidades', '10', '2727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAM-00109', 'JAMON ENDIABLADO PLUMROSE 60 GR', 'Unidades', '13', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAM-00110', 'JAMON ENDIABLADO PLUMROSE 110 GR', 'Unidades', '6', '1545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAM-00111', 'JAMON ENDIABLADO UNTABLE CHARDELI ', 'Unidades', '8', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('LEC-00112', 'LECHE LIQUIDA 1 LITRO ', 'Unidades', '0', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('LEN-00113', 'LENTEJAS GRANOS RINCON 500 GR ', 'Unidades', '4', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAL-00114', 'MALTIN POLAR BOTELLA ', 'Unidades', '24', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAY-00115', 'MAYONESA MAVESA 275 GR', 'Unidades', '22', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAY-00116', 'MAYONESA MAVESA 445 GR', 'Unidades', '15', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAY-00117', 'MAYONESA MAVEZA 910 GR ', 'Unidades', '12', '4000.00', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAY-00118', 'MAYONESA BASSI 900 GR ', 'Unidades', '6', '1000.00', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00119', 'MAIZ DE COTUFA GRANOS RINCON 500 GR ', 'Unidades', '15', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00120', 'MAIZ PILADO 500 GR ', 'Unidades', '5', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00121', 'MAIZORITOS CRUNCH FLAKES BOLSA 300 GRE', 'Unidades', '3', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00122', 'MAIZORITOS AZUCARADAS 269 GR', 'Unidades', '3', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00123', 'MAIZORITOS FRUTY AROS 269 GR', 'Unidades', '3', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAR-00124', 'MARGARINA MAVESA 250 GR ', 'Unidades', '20', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAR-00125', 'MARGARINA MAVESA 500 GR ', 'Unidades', '10', '1545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAR-00126', 'MARGARINA MAVESA 1 KG', 'Unidades', '10', '2909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00127', 'MAIZINA AMERICANA 90 GR ', 'Unidades', '4', '545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00128', 'MAIZINA AMERICANA 400 GR ', 'Unidades', '6', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00129', 'MAIZINA AMERICANA 800 GR ', 'Unidades', '4', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00130', 'MAICENA TIGO 100 GR ', 'Unidades', '5', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00131', 'MAICENA TIGO 200 GR ', 'Unidades', '9', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00132', 'MAICENA TIGO 400 GR', 'Unidades', '5', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MOR-00133', 'MORTADELA PUNTA DE MONTE POLLO 1 KG', 'Unidades', '0', '2909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MOR-00134', 'MORTADELA PUNTA DE MONTE POLLO 500GR', 'Unidades', '0', '1545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MOR-00135', 'MORTADELA ESPECIAL ARICHUNA CARNE 1 KG', 'Unidades', '0', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MOR-00136', 'MORTADELA ESPECIAL PLUMROSE CARNE 1 KG', 'Unidades', '0', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00137', 'MAIZ DULCE NUTRITEC 340 GR ', 'Unidades', '6', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MAI-00138', 'MAIZ DULCE COOLTIVO 340 GR ', 'Unidades', '5', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('LEC-00139', 'LECHE CONDENSADA WYNCO 395 GR', 'Unidades', '5', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAP-00140', 'PAPAS FRITAS MARLY 160 GR ', 'Unidades', '5', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAP-00141', 'PAPAS FRITAS MARLY 500 GR ', 'Unidades', '1', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAC-00142', 'PACK SALSAS LA VIÑA 3 UNI', 'Unidades', '5', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAC-00143', 'PACK SALSAS LA DESPENSA 3 UNI', 'Unidades', '10', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00144', 'PASTA CAPRI PREMIUM TORNILLO 1 KG', 'Unidades', '6', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00145', 'PASTA CAPRI PREMIUM PLUMA 1 KG', 'Unidades', '7', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00146', 'PASTA CAPRI PREMIUM DEDAL 1 KG', 'Unidades', '28', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00147', 'PASTA CAPRI PREMIUM CODITO 1 KG', 'Unidades', '9', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00148', 'PASTA CAPRI PREMIUM DEDALITO 1 KG', 'Unidades', '12', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00149', 'PASTA CAPRI PREMIUM ESPAGUETTINI 1 KG', 'Unidades', '28', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00150', 'PASTA CAPRI PREMIUM RIGATONI 1 KG', 'Unidades', '3', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00151', 'PASTA CAPRI PREMIUM CARACOL 500 GR ', 'Unidades', '12', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00152', 'PASTA CAPRI FIDEO 250 GR', 'Unidades', '11', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00153', 'PASTA CAPRI EXTRA ESPECIAL DEDALITO 1 KG ', 'Unidades', '12', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00154', 'PASTA CAPRI EXTRA ESPECIAL RIGATONI 1 KG ', 'Unidades', '10', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00155', 'PASTA CAPRI EXTRA ESPECIAL TORNILLO 1 KG ', 'Unidades', '8', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00156', 'PASTA CAPRI EXTRA ESPECIAL VERMICELLI FINO 1 KG ', 'Unidades', '9', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00157', 'PASTA CAPRI EXTRA ESPECIAL DEDAL 1 KG ', 'Unidades', '12', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00158', 'PASTA SINDONI PLUMA 1 KG', 'Unidades', '3', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00159', 'PASTA SINDONI TORNILLO 1 KG ', 'Unidades', '2', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00160', 'PASTA SINDONI PLUMITA 1 KG ', 'Unidades', '7', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00161', 'PASTA SINDONI VERMICELLI 1 KG ', 'Unidades', '10', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00162', 'PASTA PASTICHO CAPRI 250 GR ', 'Unidades', '8', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAS-00163', 'PASTA LASAÑA GALO 200 GR', 'Unidades', '6', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('POL-00164', 'POLVO DE HORNEAR OLYMPA 120 GR ', 'Unidades', '1', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('REF-00165', 'REFRESCO 2 LITROS', 'Unidades', '36', '1000.00', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('RIK-00166', 'RIKESA CHEDDAR 330 GR ', 'Unidades', '7', '2727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('RIK-00167', 'RIKESA CHEDDAR 200 GR ', 'Unidades', '10', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('RIK-00168', 'RIKESA CHEDDAR 300GR ', 'Unidades', '6', '2727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00169', 'SAL BAHIA 1 KG', 'Unidades', '13', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00170', 'SAL ESMERALDA 1 KG', 'Unidades', '15', '363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00171', 'SALSA BARBECUE LA VIÑA 290 GR ', 'Unidades', '6', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00172', 'SALSA PARA PIZZA OSOLE 340 GR', 'Unidades', '4', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00173', 'SALSA PARA PIZZA OLE 340 GR', 'Unidades', '10', '9090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00174', 'SALSA PARA PASTA UNDER WOOD ', 'Unidades', '5', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MOS-00175', 'MOSTAZA TIGO 180 GR ', 'Unidades', '6', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MOS-00176', 'MOSTAZA HEINZ 195 GR', 'Unidades', '8', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00177', 'SALSA DE TOMATE PAMPERO 198 GR ', 'Unidades', '5', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00178', 'SALSA DE TOMATE 397 GR', 'Unidades', '7', '1363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00179', 'SALSA DE TOMATE HEINZ 198 GR', 'Unidades', '8', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00180', 'SALSA DE TOMATE HEINZ 397 GR ', 'Unidades', '11', '1363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00181', 'SALSA DE TOMATE FERGOS 397 GR', 'Unidades', '4', '1363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00182', 'SALSA DE TOMATE CAPRI 397 GR', 'Unidades', '3', '1363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAL-00183', 'SALSA DE TOMATE TURIAMO 397 GR ', 'Unidades', '3', '1363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00184', 'SARDINA MARGARITA TOMATE 170 GR ', 'Unidades', '18', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00185', 'SARDINA MARGARITA ACEITE 170 GR', 'Unidades', '16', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00186', 'SARDINA EVEBA ACEITE 170 GR', 'Unidades', '15', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00187', 'SARDINA EVEBA TOMATE 170 GR', 'Unidades', '20', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00188', 'SARDINA EVEBA PICANTE 170 GR ', 'Unidades', '8', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00189', 'SARDINA PEÑERO ITALIANA 170 GR ', 'Unidades', '7', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00190', 'SARDINA INCOSA TOMATE 170 GR ', 'Unidades', '7', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00191', 'SARDINA TIGO TOMATE 170 GR', 'Unidades', '15', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00192', 'SARDINA TIGO ACEITE 170 GR', 'Unidades', '12', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00193', 'SARDINA MARBONITA TOMATE 170 GR', 'Unidades', '18', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00194', 'SARDINA OMEGA ACEITE 170 GR', 'Unidades', '24', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00195', 'SARDINA OMEGA TOMATE 170 GR', 'Unidades', '22', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SAR-00196', 'SARDINA MONARCA TOMATE 170 GR', 'Unidades', '26', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SOP-00197', 'SOPA MAGGI 62 GR ', 'Unidades', '26', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('VAI-00198', 'VAINILLA LA VIÑA 300 ML', 'Unidades', '4', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('VAI-00199', 'VAINILLA LA VIÑA 150 ML', 'Unidades', '8', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('VIN-00200', 'VINAGRE HEINZ 500 ML ', 'Unidades', '10', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('VIN-00201', 'VINAGRE HEINZ 1 LITRO ', 'Unidades', '5', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('VIN-00202', 'VINAGRE FRITZ 500 ML ', 'Unidades', '5', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('VIN-00203', 'VINAGRE DEL SAZON 500 ML', 'Unidades', '9', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('VIN-00204', 'VINAGRE DESPENSA 1 LITRO', 'Unidades', '2', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('VIN-00205', 'VINAGE MAVESA 1 LITRO ', 'Unidades', '8', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('VIN-00206', 'VINAGRE DELEITE 1 LITRO', 'Unidades', '7', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('VIN-00207', 'VINAGRE HEINZ 3,7 LITROS', 'Unidades', '1', '4181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('TOD-00208', 'TODDY 200 GR ', 'Unidades', '2', '2000.00', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('TOD-00209', 'TODDY 400 GR', 'Unidades', '4', '3454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ALI-00210', 'ALIMENTO PARA GATOS MAGIC FRIENDS 1 KG ', 'Unidades', '8', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ALI-00211', 'ALIMENTO PARA GATOS MIRINGO  1 KG ', 'Unidades', '12', '1818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ALI-00212', 'ALIMENTO PARA PERROS ADULTOS MIRINGO  1 KG ', 'Unidades', '13', '1545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('LAV-00213', 'LAVAPLATOS LIQUIDO BRISOL 825ML', 'Unidades', '3', '4363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('LAV-00214', 'LAVAPLATOS LIQUIDO AROMAX 1 LITRO ', 'Unidades', '3', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SUA-00215', 'SUAVISANTE BONAROPA MANZANA', 'Unidades', '6', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SUA-00216', 'SUAVISANTE BONAROPA FLLORAL ', 'Unidades', '6', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CLO-00217', 'CLORO BRILLAKING 2 LITROS', 'Unidades', '6', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CLO-00218', 'CLORO BLANCOX 500 ML ', 'Unidades', '15', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CLO-00219', 'CLORO JABONOSO AROMAX ', 'Unidades', '2', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00220', 'JABON EN POLVO ACE 400 GR', 'Unidades', '8', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00221', 'JABON EN POLVO ACE 900 GR', 'Unidades', '8', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00222', 'JABON EN POLVO ACE 4 KG', 'Unidades', '4', '8363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00223', 'JABON EN POLVO LAS LLAVES FLORAL 400 GR', 'Unidades', '7', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00224', 'JABON EN POLVO ARIEL TRIPLE PODER 1 KG ', 'Unidades', '5', '2363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00225', 'JABON EN POLVO ARIEL TRIPLE PODER 2 KG ', 'Unidades', '4', '4545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00226', 'JABON EN POLVO EDEN 1 KG ', 'Unidades', '14', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00227', 'JABON EN POLVO BONAROPA 1 KG ', 'Unidades', '13', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00228', 'JABON EN POLVO ALIVE 1 KG ', 'Unidades', '2', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00229', 'JABON EN POLVO ULTREX 250 GR', 'Unidades', '8', '545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00230', 'JABON EN POLVO ULTREX 1 KG', 'Unidades', '6', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00231', 'JABON EN POLVO PEROS 1 KG', 'Unidades', '16', '1363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00232', 'JABON EN POLVO PEROS 400 GR', 'Unidades', '9', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CEP-00233', 'CEPILLO DE BARRER MAX HOGAR ', 'Unidades', '7', '1636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00234', 'JABON AXION 235 GR ', 'Unidades', '3', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00235', 'JABON AXION 450 GR ', 'Unidades', '7', '1545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00236', 'JABON AXION 130 GR ', 'Unidades', '15', '363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('LAS-00237', 'LAS LLAVES JABON BEBE 160 GR ', 'Unidades', '14', '545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00238', 'JABON DERSA 320 GR', 'Unidades', '13', '545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00239', 'JABON DERSA 230 GR', 'Unidades', '15', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00240', 'JABON ROMBO 200 GR ', 'Unidades', '20', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00241', 'JABON FAB 200 GR', 'Unidades', '5', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00242', 'JABON FAB 300 GR', 'Unidades', '4', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('LIM-00243', 'LIMPIAPISOS SUPER B LAVANDA 960 ML ', 'Unidades', '3', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('LIM-00244', 'LIMPIAPISOS BRILLA KING LAVANDA JAZMIN 1000ML', 'Unidades', '6', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('LIM-00245', 'LIMPIAPISOS BRILLA KING MANZANA CANELA 1000ML', 'Unidades', '6', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MIS-00246', 'MISTOLIN BEBE 828 ML ', 'Unidades', '2', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('MIS-00247', 'MISTOLIN AROMATERAPIA 828 ML ', 'Unidades', '3', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CER-00248', 'CERA ROJA PARA PISOS SUPER LIMPIEX 1 LITRO', 'Unidades', '5', '1454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CER-00249', 'CERA VERDE PARA PISOS SUPER LIMPIEX 1 LITRO', 'Unidades', '6', '1454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAP-00250', 'PAPEL HIGIENICO ROSAL PLUS 4 ROLLOS 600 HOJAS', 'Unidades', '8', '2000.00', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAP-00251', 'PAPEL HIGIENICO MAPLE 4 ROLLOS 600 HOJAS', 'Unidades', '7', '1454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAP-00252', 'PAPEL HIGIENICO ELITE 12 ROLLOS', 'Unidades', '6', '3636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAÑ-00253', 'PAÑALES MEDIANOS VI&CO 22 UNI', 'Unidades', '7', '3636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAÑ-00254', 'PAÑALES GRANDES VI&CO 20 UNI', 'Unidades', '7', '3636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('TOA-00255', 'TOALLITAS HUMEDAS VI&CO 72 UNI', 'Unidades', '8', '1272.73', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SER-00256', 'SERVILLETAS RENDY 200 UNIDADES ', 'Unidades', '7', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('SER-00257', 'SERVILLETAS FAMILIA 100 UNIDADES', 'Unidades', '6', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('TOA-00258', 'TOALLIN ROSAL TOWELS ', 'Unidades', '4', '1000.00', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('TOA-00259', 'TOALLIN CARICIAS ', 'Unidades', '4', '1000.00', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAP-00260', 'PAPEL DE ALUMINIO MIO 7 METROS ', 'Unidades', '6', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAP-00261', 'PAPEL DE ALUMINIO MP 8 METROS', 'Unidades', '6', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PAP-00262', 'PAPEL DE ALIUMINIO MAX HOGAR 8 METROS ', 'Unidades', '5', '1181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CRE-00263', 'CREMA DENTAL COLGATE KIDS 50 GR ', 'Unidades', '11', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CRE-00264', 'CREMA DENTAL COLGATE 90 GR', 'Unidades', '7', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CRE-00265', 'CREMA DENTAL COLGATE 180 GR', 'Unidades', '8', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CRE-00266', 'CREMA DENTAL COLGATE TRIPLE ACCION 100 ML ', 'Unidades', '8', '1090.91', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CRE-00267', 'CREMA DENTAL COLGATE ALIDENT AZUL 50 GR', 'Unidades', '12', '454.55', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CRE-00268', 'CREMA DENTAL GALACTIC CLASSIC 180 GR', 'Unidades', '12', '1545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00269', 'JABON DE BAÑO FRAGANCIA', 'Unidades', '20', '363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00270', 'JABON DE BAÑO PROTEX  FRESH', 'Unidades', '12', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00271', 'JABON DE BAÑO PROTEX  GLICERINA', 'Unidades', '8', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00272', 'JABON DE BAÑO PROTEX AVENA', 'Unidades', '8', '727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('JAB-00273', 'JABON DE BAÑO LEMON ', 'Unidades', '12', '545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('TOA-00274', 'TOALLAS SANITARIAS NOSOTRAS INVISIBLE CLASICA 10 UNI', 'Unidades', '6', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('TOA-00275', 'TOALLAS SANITARIAS NOSOTRAS BUENAS NOCHES 10 UNI', 'Unidades', '7', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('TOA-00276', 'TOALLAS SANITARIAS NOSOTRAS PLUS CANALGEL10 UNI', 'Unidades', '6', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('PRO-00277', 'PROTECTORES DIARIOS NOSOTRAS 15 UNI ', 'Unidades', '5', '909.09', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('LOC-00278', 'LOCION CORPORAL ALIVE MANZANILLA 450 ML ', 'Unidades', '3', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('LOC-00279', 'LOCION CORPORAL ALIVE COCO TROPICAL 450 ML ', 'Unidades', '2', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CHA-00280', 'CHAMPU DAVEY ANTICASPA 400 ML ', 'Unidades', '3', '2727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('CHA-00281', 'CHAMPU DAVEY OLIVE 400 ML ', 'Unidades', '3', '2727.27', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('DEN-00282', 'DENCORUB ARNICA 80GR', 'Unidades', '6', '2545.45', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('DEN-00283', 'DENCORUB ICE 40GR', 'Unidades', '6', '2363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES (' MA-00284', ' MAGNESIA TRADICIONAL MK', 'Unidades', '8', '2181.82', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ESP-00285', 'ESPUMA DE AFEITAR GILLETTE CARBON 150 GR', 'Unidades', '3', '2363.64', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ESP-00286', 'ESPONJA MAX HOGAR ORO/PLATA', 'Unidades', '6', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ESP-00287', 'ESPONJA MAX HOGAR DOBLE USO ', 'Unidades', '8', '818.18', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ESP-00288', 'ESPONJA MAX HOGAR ACERO INOXIDABLE', 'Unidades', '7', '636.36', '1');
INSERT INTO `productos` (`codigo`, `nombre`, `medida`, `cantidad`, `precio`, `proveedor`) VALUES ('ESP-00289', 'ESPONJA MAX HOGAR SOFT', 'Unidades', '7', '2363.64', '1');
