package Sistema;

import ModeloFinal.ProductosDAO;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class AgregarStock extends javax.swing.JFrame {
    private TextAutoCompleter ac;
    ProductosDAO productos = new ProductosDAO();
    
    int xMouse;
    int yMouse;
    
    public AgregarStock() {
        initComponents();
        componentes();
         
        ac = new TextAutoCompleter(jt_nombre_agregar);
        cargarSugerenciasNombre();
    }
    
    public void componentes(){
        jt_nombre_agregar.setForeground(Color.BLACK);
        jt_cantidad_agregar.setForeground(Color.BLACK);
        jt_nombre_agregar.setBackground(Color.WHITE);
        jt_cantidad_agregar.setBackground(Color.WHITE);
        
        jl_nombre_agregar.setForeground(Color.BLACK);
        jl_cantidad_agregar.setForeground(Color.BLACK);
        
        jb_guardar_agregar.setBackground(Color.WHITE);
        jb_limpiar_agregar.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_bg_agregar = new javax.swing.JPanel();
        jt_nombre_agregar = new javax.swing.JTextField();
        jl_nombre_agregar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jl_cantidad_agregar = new javax.swing.JLabel();
        jt_cantidad_agregar = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jb_guardar_agregar = new javax.swing.JButton();
        jb_limpiar_agregar = new javax.swing.JButton();
        jp_mover = new javax.swing.JPanel();
        jp_x = new javax.swing.JPanel();
        jl_x = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_bg_agregar.setBackground(new java.awt.Color(255, 255, 255));

        jt_nombre_agregar.setBorder(null);
        jt_nombre_agregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_nombre_agregarKeyPressed(evt);
            }
        });

        jl_nombre_agregar.setText("Ingrese el nombre del producto");

        jl_cantidad_agregar.setText("Ingrese la cantidad a agregar");

        jt_cantidad_agregar.setBorder(null);

        jb_guardar_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagine/Guardar.png"))); // NOI18N
        jb_guardar_agregar.setText("GUARDAR");
        jb_guardar_agregar.setBorder(null);
        jb_guardar_agregar.setBorderPainted(false);
        jb_guardar_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardar_agregarActionPerformed(evt);
            }
        });

        jb_limpiar_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagine/Nuevo.png"))); // NOI18N
        jb_limpiar_agregar.setText("LIMPIAR");
        jb_limpiar_agregar.setBorder(null);
        jb_limpiar_agregar.setBorderPainted(false);
        jb_limpiar_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiar_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_bg_agregarLayout = new javax.swing.GroupLayout(jp_bg_agregar);
        jp_bg_agregar.setLayout(jp_bg_agregarLayout);
        jp_bg_agregarLayout.setHorizontalGroup(
            jp_bg_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_bg_agregarLayout.createSequentialGroup()
                .addGroup(jp_bg_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_bg_agregarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jp_bg_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_bg_agregarLayout.createSequentialGroup()
                                .addComponent(jl_cantidad_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addGap(275, 275, 275))
                            .addGroup(jp_bg_agregarLayout.createSequentialGroup()
                                .addComponent(jl_nombre_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(265, 265, 265))
                            .addComponent(jt_nombre_agregar)
                            .addComponent(jSeparator1)
                            .addComponent(jt_cantidad_agregar)
                            .addComponent(jSeparator2)))
                    .addGroup(jp_bg_agregarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jb_guardar_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(124, 124, 124)
                        .addComponent(jb_limpiar_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)))
                .addGap(41, 41, 41))
        );
        jp_bg_agregarLayout.setVerticalGroup(
            jp_bg_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_bg_agregarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jl_nombre_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jt_nombre_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jl_cantidad_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jt_cantidad_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jp_bg_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_guardar_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_limpiar_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jp_bg_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jp_mover.setBackground(new java.awt.Color(255, 255, 255));
        jp_mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jp_moverMouseDragged(evt);
            }
        });
        jp_mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jp_moverMousePressed(evt);
            }
        });

        jp_x.setBackground(new java.awt.Color(255, 255, 255));

        jl_x.setBackground(new java.awt.Color(0, 0, 0));
        jl_x.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jl_x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_x.setText("X");
        jl_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jl_xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jl_xMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jp_xLayout = new javax.swing.GroupLayout(jp_x);
        jp_x.setLayout(jp_xLayout);
        jp_xLayout.setHorizontalGroup(
            jp_xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_xLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_x, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jp_xLayout.setVerticalGroup(
            jp_xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_xLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jl_x, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jp_moverLayout = new javax.swing.GroupLayout(jp_mover);
        jp_mover.setLayout(jp_moverLayout);
        jp_moverLayout.setHorizontalGroup(
            jp_moverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_moverLayout.createSequentialGroup()
                .addComponent(jp_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 492, Short.MAX_VALUE))
        );
        jp_moverLayout.setVerticalGroup(
            jp_moverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_moverLayout.createSequentialGroup()
                .addComponent(jp_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jp_mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jp_moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_moverMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jp_moverMousePressed

    private void jp_moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_moverMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jp_moverMouseDragged

    private void jl_xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_xMouseEntered
        // TODO add your handling code here:
        jp_x.setBackground(Color.RED);
        jl_x.setForeground(Color.WHITE);
    }//GEN-LAST:event_jl_xMouseEntered

    private void jl_xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_xMouseExited
        // TODO add your handling code here:
        jp_x.setBackground(Color.WHITE);
        jl_x.setForeground(Color.BLACK);
    }//GEN-LAST:event_jl_xMouseExited

    private void jl_xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_xMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jl_xMouseClicked

    private void jb_guardar_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardar_agregarActionPerformed
        String nombre = jt_nombre_agregar.getText();
        double cantidad = Double.parseDouble(jt_cantidad_agregar.getText());
        productos.actualizarStock(nombre, cantidad);
        jt_nombre_agregar.setText("");
        jt_cantidad_agregar.setText("");
        JOptionPane.showMessageDialog(null, "Stock actualizado correctamente");
    }//GEN-LAST:event_jb_guardar_agregarActionPerformed

    private void jb_limpiar_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiar_agregarActionPerformed
        jt_nombre_agregar.setText("");
        jt_cantidad_agregar.setText("");
    }//GEN-LAST:event_jb_limpiar_agregarActionPerformed

    private void jt_nombre_agregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_nombre_agregarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jt_cantidad_agregar.requestFocus();
        }
    }//GEN-LAST:event_jt_nombre_agregarKeyPressed

    private void cargarSugerenciasNombre() {
        String[] tempNombre = productos.cargarSugerenciasNombre();
        ac.removeAllItems();
        for (int i = 0; i < tempNombre.length; i++) {
            ac.addItem(tempNombre[i]);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jb_guardar_agregar;
    private javax.swing.JButton jb_limpiar_agregar;
    private javax.swing.JLabel jl_cantidad_agregar;
    private javax.swing.JLabel jl_nombre_agregar;
    private javax.swing.JLabel jl_x;
    private javax.swing.JPanel jp_bg_agregar;
    private javax.swing.JPanel jp_mover;
    private javax.swing.JPanel jp_x;
    private javax.swing.JTextField jt_cantidad_agregar;
    public javax.swing.JTextField jt_nombre_agregar;
    // End of variables declaration//GEN-END:variables
}
