/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema;

import login.*;
import ModeloFinal.Login;
import ModeloFinal.LoginDAO;
import Sistema.Sistema;
import java.awt.Color;

/**
 *
 * @author PC
 */
public class Registro extends javax.swing.JFrame {

    Login log = new Login();
    LoginDAO login = new LoginDAO();
    /**
     * Creates new form Login
     */
    public Registro() {
        initComponents();
    }
    
    public void validadDatosLogin(){
        String nombre = JT_Usuario.getText();
        String password = String.valueOf(JT_Password.getPassword());
        if(!"".equals(nombre) || !"".equals(password)){
            log = login.log(nombre, password);
            if(log.getNombre() != null && log.getPassword() != null){
                Sistema sistema = new Sistema(log.getNombre());
                sistema.setVisible(true);
                dispose();
            }else
                javax.swing.JOptionPane.showMessageDialog(this, "Los datos ingresados son incorrectos.");
        }
    }
    
    /**
     * Variables
     */

    int xMouse, yMouse;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_bg = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        JP_ExitBT = new javax.swing.JPanel();
        JL_TextX = new javax.swing.JLabel();
        JP_MenuIZ = new javax.swing.JPanel();
        JL_Titulo = new javax.swing.JLabel();
        JL_Usuario = new javax.swing.JLabel();
        JT_Usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        JL_Password = new javax.swing.JLabel();
        JT_Password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        JL_Password1 = new javax.swing.JLabel();
        JT_Password1 = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        JL_Usuario1 = new javax.swing.JLabel();
        JT_Usuario1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        JP_Button = new javax.swing.JPanel();
        JL_Button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        JP_bg.setBackground(new java.awt.Color(204, 204, 204));
        JP_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        JP_ExitBT.setBackground(new java.awt.Color(255, 255, 255));

        JL_TextX.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JL_TextX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_TextX.setText("X");
        JL_TextX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JL_TextX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JL_TextXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_TextXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_TextXMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JP_ExitBTLayout = new javax.swing.GroupLayout(JP_ExitBT);
        JP_ExitBT.setLayout(JP_ExitBTLayout);
        JP_ExitBTLayout.setHorizontalGroup(
            JP_ExitBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_ExitBTLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JL_TextX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JP_ExitBTLayout.setVerticalGroup(
            JP_ExitBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_ExitBTLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JL_TextX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(JP_ExitBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(JP_ExitBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JP_bg.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 30));

        JP_MenuIZ.setBackground(new java.awt.Color(255, 255, 255));
        JP_MenuIZ.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));

        JL_Titulo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        JL_Titulo.setText("REGISTRAR USUARIO");

        JL_Usuario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        JL_Usuario.setText("USUARIO");

        JT_Usuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JT_Usuario.setForeground(new java.awt.Color(204, 204, 204));
        JT_Usuario.setText("Ingrese su nombre de usuario");
        JT_Usuario.setBorder(null);
        JT_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JT_UsuarioMousePressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        JL_Password.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        JL_Password.setText("CONTRASEÑA");

        JT_Password.setForeground(new java.awt.Color(204, 204, 204));
        JT_Password.setText("********");
        JT_Password.setBorder(null);
        JT_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JT_PasswordMousePressed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        JL_Password1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        JL_Password1.setText("CONTRASEÑA");

        JT_Password1.setForeground(new java.awt.Color(204, 204, 204));
        JT_Password1.setText("********");
        JT_Password1.setBorder(null);
        JT_Password1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JT_Password1MousePressed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        JL_Usuario1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        JL_Usuario1.setText("USUARIO");

        JT_Usuario1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JT_Usuario1.setForeground(new java.awt.Color(204, 204, 204));
        JT_Usuario1.setText("Ingrese su nombre de usuario");
        JT_Usuario1.setBorder(null);
        JT_Usuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JT_Usuario1MousePressed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        JP_Button.setBackground(new java.awt.Color(157, 149, 210));

        JL_Button.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        JL_Button.setForeground(new java.awt.Color(255, 255, 255));
        JL_Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL_Button.setText("ENTRAR");
        JL_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JL_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JL_ButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JL_ButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JL_ButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout JP_ButtonLayout = new javax.swing.GroupLayout(JP_Button);
        JP_Button.setLayout(JP_ButtonLayout);
        JP_ButtonLayout.setHorizontalGroup(
            JP_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_ButtonLayout.createSequentialGroup()
                .addComponent(JL_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JP_ButtonLayout.setVerticalGroup(
            JP_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_ButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JL_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout JP_MenuIZLayout = new javax.swing.GroupLayout(JP_MenuIZ);
        JP_MenuIZ.setLayout(JP_MenuIZLayout);
        JP_MenuIZLayout.setHorizontalGroup(
            JP_MenuIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_MenuIZLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(JL_Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_MenuIZLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(JP_MenuIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_Password)
                    .addGroup(JP_MenuIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JT_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JP_MenuIZLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(JP_MenuIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JL_Password1)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(JP_MenuIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JL_Usuario1)
                                    .addComponent(JT_Usuario1)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(JP_MenuIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JT_Password, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_MenuIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JL_Usuario)
                        .addComponent(JT_Usuario)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_MenuIZLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(JP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)))
                .addGap(40, 40, 40))
        );
        JP_MenuIZLayout.setVerticalGroup(
            JP_MenuIZLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_MenuIZLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(JL_Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JT_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JL_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JT_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL_Usuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JT_Usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JL_Password1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JT_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(JP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        JP_bg.add(JP_MenuIZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 460, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_bg, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    //Mouse arrastra la ventana
    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        //Obtener posicion mouse pantalla
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void JL_TextXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_TextXMouseEntered
        JP_ExitBT.setBackground(Color.red);
        JL_TextX.setForeground(Color.WHITE);
    }//GEN-LAST:event_JL_TextXMouseEntered

    private void JL_TextXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_TextXMouseExited
        JP_ExitBT.setBackground(Color.WHITE);
        JL_TextX.setForeground(Color.BLACK);
    }//GEN-LAST:event_JL_TextXMouseExited

    private void JL_TextXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_TextXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_JL_TextXMouseClicked

    private void JT_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_UsuarioMousePressed
        if(JT_Usuario.getText().equals("Ingrese su nombre de usuario")){
            JT_Usuario.setText("");
            JT_Usuario.setForeground(Color.BLACK);
        }
        if(String.valueOf(JT_Password.getPassword()).isEmpty()){
            JT_Password.setText("********");
            JT_Password.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_JT_UsuarioMousePressed

    private void JT_Password1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_Password1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_Password1MousePressed

    private void JT_Usuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_Usuario1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_Usuario1MousePressed

    private void JT_PasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_PasswordMousePressed
        if(String.valueOf(JT_Password.getPassword()).equals("********")){
            JT_Password.setText("");
            JT_Password.setForeground(Color.BLACK);
        }
        if(JT_Usuario.getText().isEmpty()){
            JT_Usuario.setText("Ingrese su nombre de usuario");
            JT_Usuario.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_JT_PasswordMousePressed

    private void JL_ButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_ButtonMousePressed
        validadDatosLogin();
    }//GEN-LAST:event_JL_ButtonMousePressed

    private void JL_ButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_ButtonMouseExited
        JP_Button.setBackground(new Color(157,149,210));
    }//GEN-LAST:event_JL_ButtonMouseExited

    private void JL_ButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JL_ButtonMouseEntered
        JP_Button.setBackground(new Color(157, 170, 249));
    }//GEN-LAST:event_JL_ButtonMouseEntered

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel JL_Button;
    private javax.swing.JLabel JL_Password;
    private javax.swing.JLabel JL_Password1;
    private javax.swing.JLabel JL_TextX;
    private javax.swing.JLabel JL_Titulo;
    private javax.swing.JLabel JL_Usuario;
    private javax.swing.JLabel JL_Usuario1;
    private javax.swing.JPanel JP_Button;
    private javax.swing.JPanel JP_ExitBT;
    private javax.swing.JPanel JP_MenuIZ;
    private javax.swing.JPanel JP_bg;
    private javax.swing.JPasswordField JT_Password;
    private javax.swing.JPasswordField JT_Password1;
    private javax.swing.JTextField JT_Usuario;
    private javax.swing.JTextField JT_Usuario1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
